import Head from "next/head";
import { Navigation } from "../components/Navigation";
import { Card } from "../components/Card";
import { Menu } from "../components/Menu";
export default function Home() {

  const items = [
    {
      name: "Home",
      desc: "Description Home",
      link: "/",
    },
    {
      name: "Portfolio",
      desc: "Description Portfolio",
      link: "/portfolio",
    },
    {
      name: "About me",
      desc: "Description About me",
      link: "/about",
    },
    {
      name: "Contact",
      desc: "Description Contact",
      link: "/contact",
    }
  ]
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div>
          <Menu>
            <Navigation
              items={items}
            />
          </Menu>
          <Card />
        </div>
      </div>
    </>
  );
}
